name: First React Workflow
on:
 push:
 pull_request:
  branches:
    - main
jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          node-version: 24
          cache: npm

      - name: install dependencies
        run: npm install

      - name: running eslint
        run: npx eslint src


  run-eslint:
    runs-on: ubuntu-latest

    steps:

     - name: checkout code
       uses: actions/checkout@v4

     - name: install node in vm
       uses:  actions/setup-node@v4
       with:
        node-version: 24
        npm-cache: true

     - name: install dependency
       run: npm install

     - name: run eslint
       run: npx eslint src

  create-build:
    needs: [install-dependencies,run-eslint]
    runs-on: ubuntu-latest

    env:
      VERCEL_PROJECT_ID: "${{secrets.VERCEL_PROJECT_ID}}"
      VERCEL_TEAM_ID: "${{secrets.VERCEL_TEAM_ID}}"

    steps:

      - name: checkout code
        uses: actions/checkout@v4     

      - name: install node in vm
        uses:  actions/setup-node@v4
        with:
          node-version: 24
          npm-cache: true   

      - name: install dependency
        run: npm install    

      - name: create build
        run: CI=false npm run build   

      - name: create artifact
        uses: actions/upload-artifact@v4
        with:
            name: react-build
            path: build/
            retention-days: 7

      - name: install vercel cli
        run: npm install --global vercel

      - name: deployment on vercel
        run: vercel deploy build --prod --yes --token="${{secrets.VERCEL_TOKEN}}"       

  # deploy-job:
  #   needs: [install-dependencies,run-eslint,create-build]
  #   runs-on: ubuntu-latest 

  #   steps:         

  #     - name: checkout code
  #       uses: actions/checkout@v4      

  #     - name: Download build artifact
  #       uses: actions/download-artifact@v5
  #       with:
  #         name: react-build

           


