name: First React Workflow
on:
 push:
 pull_request:
  branches:
    - main
jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          node-version: 24
          cache: npm

      - name: install dependencies
        run: npm install

      - name: running eslint
        run: npx eslint src


  run-eslint:
    runs-on: ubuntu-latest

    steps:

     - name: checkout code
       uses: actions/checkout@v4

     - name: install node in vm
       uses:  actions/setup-node@v4
       with:
        node-version: 24
        npm-cache: true

     - name: install dependency
       run: npm ci

     - name: run eslint
       run: npx eslint src

  create-build:
    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v4     

      - name: install node in vm
        uses:  actions/setup-node@v4
        with:
          node-version: 24
          npm-cache: true   

      - name: install dependency
        run: npm ci    

      - name: create build
        run: CI=false npm run build   

      - name: create artifact
        uses: actions/upload-artifact@v4
        with:
            name: react-build
            path: build/
            retention-days: 7


