name: First Worklow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Github Actions
        run: echo "Hello this is the first workflow in github actions"
      - name: Bye Github Actions
        run: echo "Bye github actions"
      # - name: Intentionally failing
      #   run: exit 1  
        
      
