name: First React Workflow
on:
 push:
 pull_request:
  branches:
    - main
jobs:
  install-dependencies-create-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          node-version: 24
          cache: npm

      - name: install dependencies
        run: npm install

      - name: create build
        run: CI=false npm run build       
