name: Second Workflow
on:
 push:
 workflow_dispatch:
jobs:
    weather-app-start-job:
      runs-on: ubuntu-latest
      steps:
       - name: "welcome"
         run: echo "Welcome to the weather-app. Starting the workflow job"

    weather-app-end-job:
      runs-on: ubuntu-latest
      steps:
      - name: "bye"
        run: echo "Hello user. closing the workflow job"

